### ISSUE TITLE
Issue while processing NA in matrix input file

### ISSUE THREAD

**Issue by sachingadakh** [dozmorovlab/SpectralTAD#6]
Hello,
I am trying to process the matrix file n×(n+3) with NAs for non-interacting regions. 
However, I am facing an error while running the SpectralTAD function, such as :
Error in SpectralTAD(readmatgam, chr = "chr12", resolution = 50000, window_size = 400000,  : 
  Contact matrix must only contain real numbers

Now replacing NA with any number, especially 0, as TopDom recommends, would produce false positive TADs. 
So I would appreciate it if you could guide me on how to handle/process NAs using SpectralTAD. 
Thank you

**Comment by mdozmorov** [comment]
Hi @sachingadakh, the simplest solution would be to use lower-resolution data with fewer NAs. Replacing them with 0 is OK, but when there are too many, there just won't be enough information for matrix decomposition. There's no way around it, other than deeper sequencing, or combining replicates. This would be true for most TAD callers, even those that use the directionality index or insulation score.

**Comment by mdozmorov** [comment]
Closing because it's the data problem, not SpectralTAD. Please, ask if lower-resolution data won't work (it should).
