### ISSUE TITLE
Sparse cool matrix as input

### ISSUE THREAD

**Issue by FlavianR** [dozmorovlab/SpectralTAD#9]
Hi! Thanks for this great tool!!
I have an issue when I want to use it with sparse matrix from a cool format (more precisely a mcool format). 
I generated my sparse matrix as you showed in the documentation, but it's didn't work for SpectralTAD (I used the matrix for TADCompare). 
![image](https://github.com/dozmorovlab/SpectralTAD/assets/97506200/e07018ec-537b-4691-8524-92a1e2aaec43)

I obtained this sparse matrix (the number of chromosomes is not the problem, it's the data test from Cooler/Cooltools)
![image](https://github.com/dozmorovlab/SpectralTAD/assets/97506200/1813093e-8945-48e4-8fe2-279c70cdbde2)

And I got this Error 
![image](https://github.com/dozmorovlab/SpectralTAD/assets/97506200/4a49b119-4722-4ac3-a804-3f75bdb92899)
(I try with and without the precision of Levels)

Do you know what I did wrong ?

**Comment by mdozmorov** [comment]
Does this error occur with the latest version of SpectralTAD? It looks familiar and I think we fixed it a while ago. Try 
```{r}
devtools::install_github('dozmorovlab/SpectralTAD', build_vignettes = TRUE)
```

Also, I'd recommend basic debugging - make a one-chromosome object (not list), run SpectralTAD on it with the default settings, if it breaks, compare your object with the one provided with the package - what are the differences?

**Comment by FlavianR** [comment]
Thanks for the fast reply. 
It's working with the last version (I had install it with BiocManager, thereforce not the last version). 

Thanks a lot for all your works!!

**Comment by mdozmorov** [comment]
I'll check the Bioconductor code, it should be in sync with this repo. Strange it didn't work with BiocInstaller.
